# Generated by Django 4.2.5 on 2023-09-18 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_user_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='user',
        ),
    ]
