# Generated by Django 4.2.5 on 2023-09-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_habit_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
