# Generated by Django 4.2.5 on 2023-09-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_alter_habit_created_at_habitcompletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitcompletion',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
