# Generated by Django 4.2.5 on 2023-09-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_alter_habitcompletion_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitcompletion',
            name='date_today',
            field=models.DateField(),
        ),
    ]
